project:
  type: book
  output-dir: docs
  resources:
    - examples/hr.sql
    - examples/hr-SQL-Sample-Database-Schema.png
    - examples/sample-query.sql
  render:
    - index.qmd
    - examples/query-garden.qmd
    - examples/query-garden-python.qmd
    - examples/query-garden-r.qmd
    - examples/revealjs.qmd

book:
  title: "Query Garden"
  author: "Nakul R. Padalkar"
  chapters:
    - index.qmd
    - examples/query-garden.qmd
    - examples/query-garden-python.qmd
    - examples/query-garden-r.qmd
    - examples/revealjs.qmd

format:
  html:
    code-tools: true
    toc: true
